name: test-and-deploy
on: push

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn install --production
      - name: Deploy
        run: "yarn firebase:deploy -m \"Deploy from GitHub: ${GITHUB_SHA}\""
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
