name: test-and-deploy
on: push

jobs:
  check_formatting:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn install
      - name: Run prettier
        run: yarn prettier:check
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn install
      - name: Run eslint
        run: yarn lint && yarn functions:lint
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    needs:
      - check_formatting
      - lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: yarn install --production
      - name: Deploy
        run: 'yarn firebase:deploy --project ${FIREBASE_PROJECT} -m "Deploy from GitHub: ${GITHUB_SHA}"'
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
